name: Swift macOS build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:

    runs-on: [self-hosted, macos-12]

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: swift test --parallel
